serviceBinaries:
  openim-crontask: 1
  openim-msggateway: 1
  openim-api: 1
  openim-cmdutils: 1
  openim-push: 1
  openim-rpc-auth: 1
  openim-rpc-conversation: 1
  openim-msgtransfer: 1
  openim-rpc-friend: 1
  openim-rpc-group: 1
  openim-rpc-third: 1
  openim-rpc-msg: 1
  openim-rpc-user: 1
toolBinaries:
  - imctl
  - changelog
  - check-free-memory
  - ncpu
  - infra
  - yamlfmt
  - versionchecker
  - url2im
  - check-component
maxFileDescriptors: 10000
