username: ''
password: ''
producerAck: ""
compressType: "none"
address: [ 172.16.1.57:19094 ]
toRedisTopic: "toRedis"
toMongoTopic: "toMongo"
toPushTopic: "toPush"
toRedisGroupID: redis
toMongoGroupID: mongo
toPushGroupID: push
tls:
  enableTLS: false
  caCrt: ""
  clientCrt: ""
  clientKey: ""
  clientKeyPwd: ""
  insecureSkipVerify: false
